name: 'Deploy to EKS'
description: 'Deploy to EKS'
inputs:
  cluster_name:
    description: Name of the Kubernetes cluster
    required: true
  cluster_server:
    description: Server address of the Kubernetes cluster
    required: true
  cluster_user:
    description: Name of the Kubernetes cluster user
    required: true
  kubernetes_bearer_token:
    description: Bearer token of the cluster role
    required: true
runs:
  using: 'docker'
  image: 'docker://finvia/krane:1.1.4.6'
  env:
    CLUSTER_NAME: ${{ inputs.cluster_name }}
    CLUSTER_SERVER: ${{ inputs.cluster_server }}
    CLUSTER_USER: ${{ inputs.cluster_user }}
    KUBERNETES_BEARER_TOKEN: ${{ inputs.kubernetes_bearer_token }}
    
